config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show
  resources :classrooms
  resources :participations, only: [:destroy, :create]
  resources :posts, only: [:create, :destroy]

  root "pages#home"
  get "/*page" => "pages#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :participations
  has_many :users, through: :participations

  belongs_to :course
  belongs_to :semester
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :classrooms
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :classroom

  validates :user, presence: true
  validates :classroom, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments

  belongs_to :user
  belongs_to :classroom

  validates :user_id, presence: true
  validates :classroom_id, presence: true
  validates :content, presence: true
  validates :title, presence: true
  validate  :picture_size

  mount_uploader :picture, PictureUploader

  default_scope -> {order(created_at: :desc)}

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/models/school.rb
class School < ApplicationRecord
  has_many :users
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :classrooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable

  before_save :use_identify_to_create_email

  validates :name, presence: true, length: {maximum: 50}
  validates :identify_number, presence: true, length: {maximum: 8},
    numericality: {only_integer: true}, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}

  has_many :comments
  has_many :posts, dependent: :destroy
  has_many :bookmarks
  has_many :participations
  has_many :classrooms, through: :participations

  belongs_to :school

  private

  def use_identify_to_create_email
    self.email = "#{self.identify_number}@student.hust.edu.vn"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale
  before_action :authenticate_user!

  private

  def default_url_options options = {}
    {locale: I18n.locale}.merge options
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit :identify_number, :password, :remember_me
    end
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit :identify_number, :password, :name, :school_id
    end
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def index
    @classrooms = Classroom.all
  end

  def show
    @classroom = Classroom.find_by id: params[:id]
    @post = current_user.posts.build
    if @classroom.nil?
      flash[:danger] = t ".danger"
      redirect_to root_url
    end
    @posts = @classroom.posts
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, except: :show

  def show
    if valid_page?
      render template: "pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def create
    @classroom = Classroom.find_by id: params[:classroom_id]
    current_user.participations.create! classroom_id: @classroom.id
    redirect_to @classroom
  end

  def destroy
    @classroom = Participation.find_by(id: params[:id]).classroom
    current_user.participations.destroy params[:id]
    redirect_to @classroom
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user, only: :destroy
  def create
    @post = current_user.posts.build post_params
    if @post.save
      flash[:success] = "Post created!"
      redirect_to @post.classroom
    else
      flash[:danger] = "Can't create post, try again!"
      redirect_to :back
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

  def post_params
    params.require(:post).permit :content, :title, :classroom_id, :picture
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by id: params[:id]
    if @user.nil?
      flash[:danger] = t ".danger"
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/classrooms/_introduction.html.erb
<%= t(".title").html_safe %>

app/views/classrooms/_join.html.erb
<%= form_for @classroom.participations.new do |f| %>
  <div><%= hidden_field_tag :classroom_id, params[:id] %></div>
  <%= f.submit t(".button"), class: "btn btn-primary" %>
<% end %>

app/views/classrooms/_join_out_form.html.erb
<% if @classroom.users.include? current_user %>
  <%= render "out" %>
<% else %>
  <%= render "join" %>
<% end %>

app/views/classrooms/_out.html.erb
<%= form_for @classroom.participations.find_by(user_id: current_user.id),
  html: {method: :delete} do |f| %>
  <%= f.submit t(".button"), class: "btn" %>
<% end %>

app/views/classrooms/_posts.html.erb
<div class="row">
  <div class="col-sm-9">
    <%= t(".all_posts").html_safe %>
    <% if @classroom.posts.any? %>
      <h3>Posts (<%= @classroom.posts.count %>)</h3>
      <ol class="posts">
        <%= render @posts %>
      </ol>
    <% end %>
  </div>
  <div class="col-sm-3">
    <%= t(".order_by_date").html_safe %>
  </div>
</div>

app/views/classrooms/index.html.erb
<% provide :title, t(".title") %>
 <h1><%= t ".title" %></h1>
	<input type="text" class="live-search-box" placeholder="search here" />
	<ul class="live-search-list">

	 <% @classrooms.each do |classroom| %>
    <li><%= link_to classroom.class_code, classroom %></li>
  <% end %>
	</ul>

app/views/classrooms/show.html.erb
<% provide :title, @classroom.class_code %>
<div class="row">
	<div class="col-sm-3">
		<h1 class="classes"><%= t ".title" %> <%= @classroom.class_code %></h1>
	</div>

	<% if @classroom.users.include? current_user %>
	<div class="col-sm-offset-5 col-sm-1">
		<h1 class="classes1" >hello:</h1>
	</div>

	<div class="col-sm-3">
 	 	<section class="user_info">
  	  <%= render "shared/user_info" %>
 	 	</section>
  </div>
</div>
  <section class="post_form">
    <%= render "shared/post_form" %>
  </section>
  <%= render "classrooms/posts" %>
<% else %>
  <%= render "classrooms/introduction" %>
<% end %>
<%= render "join_out_form" %>

app/views/layouts/_dialog.erb
<div class="modal fade login" id="loginModal">
          <div class="modal-dialog login animated">
              <div class="modal-content">
                 <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Login with</h4>
                    </div>
                    <div class="modal-body">  
                        <div class="box">
                             <div class="content">
                                <div class="social">
                                    <a class="circle github" href="/auth/github">
                                        <i class="fa fa-github fa-fw"></i>
                                    </a>
                                    <a id="google_login" class="circle google" href="/auth/google_oauth2">
                                        <i class="fa fa-google-plus fa-fw"></i>
                                    </a>
                                    <a id="facebook_login" class="circle facebook" href="/auth/facebook">
                                        <i class="fa fa-facebook fa-fw"></i>
                                    </a>
                                </div>
                                <div class="division">
                                    <div class="line l"></div>
                                      <span>or</span>
                                    <div class="line r"></div>
                                </div>
                                <div class="error"></div>
                                <div class="form loginBox">
                                    <form method="post" action="/login" accept-charset="UTF-8">
                                    <input id="email" class="form-control" type="text" placeholder="Identify Number" name="email">
                                    <input id="password" class="form-control" type="password" placeholder="Password" name="password">
                                    <input class="btn btn-default btn-login" type="button" value="Login" onclick="loginAjax()">
                                    </form>
                                </div>
                             </div>
                        </div>
                        <div class="box">
                            <div class="content registerBox" style="display:none;">
                             <div class="form">
                                <form method="post" html="{:multipart=>true}" data-remote="true" action="/register" accept-charset="UTF-8">
                                <input id="email" class="form-control" type="text" placeholder="Identify Number" name="email">
                                <input id="email" class="form-control" type="text" placeholder="Name" name="email">
                                <input id="email" class="form-control" type="text" placeholder="Department" name="email">
                                <input id="password" class="form-control" type="password" placeholder="Password" name="password">
                                <input id="password_confirmation" class="form-control" type="password" placeholder="Repeat Password" name="password_confirmation">
                                <input class="btn btn-default btn-register" type="submit" value="Create account" name="commit">
                                </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="forgot login-footer">
                            <span>Looking to 
                                 <a href="javascript: showRegisterForm();">create an account</a>
                            ?</span>
                        </div>
                        <div class="forgot register-footer" style="display:none">
                             <span>Already have an account?</span>
                             <a href="javascript: showLoginForm();">Login</a>
                        </div>
                    </div>        
              </div>
          </div>
      </div>

app/views/layouts/_footer.html.erb
<footer class = "footer">
  <ul>This is footer</ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".s_plus"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".classes"), classrooms_path %></li>
        <li><%= link_to t(".bookmarks"), "#" %></li>
        <li><%= link_to t(".notification"), "#" %></li>
        <% if current_user %>
          <li><%= link_to t(".profile"), "#" %></li>
          <li><%= link_to t(".sign_out"), destroy_user_session_path, method: :delete %><li>
        <% else %>
          <li><%= link_to t(".sign_in"), new_user_session_path %></li>
          <li><%= link_to t(".sign_up"), new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
     "data-turbolinks-track": "reload" %>

     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  </head>
  <body>

  <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">
      <%= yield %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% provide :title, t(".title") %>
<div class="center jumbotron">
  <h1><%= t ".home" %></h1>
</div>

app/views/posts/_post.html.erb
<li id= "post-<%= post.id %>" >
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="title"><%= post.title %></span>
  <span class="content">
    <%= post.content %>
    <%= image_tag post.picture.url if post.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
    <% if current_user == post.user %>
      <%= link_to "delete", post, method: :delete,
        data: {confirm: "You sure?"} %>
    <% end %>
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <p> <%= f.text_field :title, placeholder: "Title..." %> </p>
    <p> <%= f.text_area :content, placeholder: "Compose new post..." %> </p>
    <div> <%= f.hidden_field :classroom_id, value: params[:id] %> </div>
  </div>
  <form class = "form-inline">
    <div class="form-group">
    <%= f.submit "Post", class: "btn btn-primary" %>
    <span class="picture ">
      <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
    </span>
    </div>
  </form>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>

app/views/static_pages/bookmarks.html.erb
<% provide :title, "Bookmarks" %>
<div class = "center jumbotron">
  <h1>This is Bookmarks</h1>
</div>

app/views/static_pages/group.html.erb
<% provide :title, "Group" %>
<div class = "center jumbotron">
  <h1>This is Group</h1>
</div>

app/views/static_pages/home.html.erb
<% provide :title, "Home" %>
<div class = "center jumbotron">
  <h1>This is Home</h1>
</div>

app/views/static_pages/notification.html.erb
<% provide :title, "Notification" %>
<div class = "center jumbotron">
  <h1>This is Notification</h1>
</div>

app/views/static_pages/profile.html.erb
<% provide :title, "Profile" %>
<div class = "center jumbotron">
  <h1>This is Profile</h1>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<h1> <%= t ".name" %>: <%= @user.name %> </h1>
<h1> <%= t ".identify_number" %>: <%= @user.identify_number %> </h1>
<h1> <%= t ".email" %>: <%= @user.email %> </h1>
<h1>
<% @user.classrooms.each do |classroom| %>
  <li><%= link_to classroom.class_code, classroom %></li>
<% end %>
</h1>